### ISSUE TITLE
Running after hooks after switching to an iframe causes timeout error if the hook uses elements outside of the iframe.

### ISSUE THREAD

**Issue by kapoorlakshya** [watir/watir#876]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.142.3
Browser Version: Chrome 76
Browser Driver Version: 76.0.3809.68
OS Version: Windows 10

## Expected Behavior

Frame switching should be successful when the after hook attempts to interact with an element outside of the `iframe`. My use case is that I am using the `after_hooks` to wait while the page load spinner is present after clicking a link that launches a dialog with an `iframe`.

## Actual Behavior

Timeout occurs when I attempt to interact with an element inside the `iframe`. Here's the stack trace from the reproducible test script included below.

```
Traceback (most recent call last):
        2: from frame_wait.rb:24:in `<main>'
        1: from I:/Opt/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.16.5/lib/watir/wait.rb:125:in `wait_until'
I:/Opt/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.16.5/lib/watir/wait.rb:46:in `until': timed out after 30 seconds, waiting for true condition on #<Watir::D
iv: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> (Watir::Wait::TimeoutError)
```

I have tracked down the cause to commit be1cd21ee2872642fc63b754801fc10e1e36917b. Frame switching is successful if I revert this commit.

#### HTML

```html
# Save as frame_test.html

<html lang="en">
  <body>
    <h1 id="page_title">Page Title</h1>
    <iframe id="watir" src="http://watir.com" height="600px" width="600px"></iframe>
  </body>
</html>
```

#### Gemfile

```
gem 'webdrivers', '~> 4.1.0'
gem 'ffi' # On Windows
gem 'watir', '~> 6.16.0'
```

#### Test Script

```ruby
require 'webdrivers'
require 'watir'

@browser = Watir::Browser.new :chrome
heading_check     = proc { @heading_found = @browser.h1(id: 'page_title').present? }
@browser.after_hooks.add heading_check

# Navigate to test page
@browser.goto File.join('file://', File.expand_path('frame_test.html'))

# IFrame should be present
puts "IFrame found: #{@browser.iframe(id: 'watir').present?}"

# Look for Div inside iframe
puts "Div text: #{@browser.iframe(id: 'watir').div(class: 'intro').text}"

# Check for presence of heading element outside the iframe.
puts "Heading found: #{@heading_found}"

@browser.close
```

I have hosted this code in a repo here - https://github.com/kapoorlakshya/watir_iframe_switching_test

**Comment by kapoorlakshya** [comment]
Ah, this is an error on my part - I wasn't using a `proc` for the hook. Changing the above test script to the following fixes the problem:

```
my_after_hook = proc { @browser.h1(id: 'page_title').present? }
@browser.after_hooks.add my_after_hook
```

**Comment by kapoorlakshya** [comment]
Ignore my previous comment. This is still a valid issue. I've updated the test script based on the example in the spec and the timeout still happens.

**Comment by MatthewMazaika** [comment]
it looks like the fix I came up with for #886 will get your test case to pass :thinking:

**Comment by MatthewMazaika** [comment]
it looks like the fix I came up with for #886 will get your test case (in your repo) to not fail with a timeout

but i don't believe the results are what you're going after

```
$ bundle exec ruby frame_wait.rb 
IFrame found: true
Div text: Watir is...
An open source Ruby library for automating tests. Watir interacts with a browser the same way people do: clicking links, filling out forms and validating text.
     Get Started Now...
require 'watir'

browser = Watir::Browser.new

browser.goto 'watir.com'
browser.link(text: 'Guides').click

puts browser.title
# => 'Guides – Watir Project'
browser.close
Heading found: false
```

it looks like the hook is still somehow running within the context of the frame, so your assertion at the end doesn't actually find the heading since it isn't within your last accessed frame

but, something I just tripped over and I'm working through it to see if it's related to #886 or not, but i think it boils down to this:

```
require 'webdrivers'
require 'watir'

@browser = Watir::Browser.new :chrome
hook     = proc { @heading_found = @browser.h1(id: 'page_title').present? }
@browser.after_hooks.add hook

# Navigate to test page
@browser.goto File.join('file://', File.expand_path('frame_test.html'))

# Look for Div inside iframe
puts "Div text: #{@browser.iframe(id: 'watir').div(class: 'intro').text}"

# then look again
puts "Div text: #{@browser.iframe(id: 'watir').div(class: 'intro').text}"

@browser.close
```

it seems very much like #886 where we can't make a second call inside the frame, but this time if there is an after hook that's accessing the dom and throwing it for a loop :thinking:

**Comment by kapoorlakshya** [comment]
@MatthewMazaika Thanks for spending time on this. Unfortunately, I am no longer using `watir` in my new role, but it would be nice to see this bug fixed soon. Good luck! :)

**Comment by titusfortner** [comment]
I think this was fixed by 886, we can reopen if it wasn't

**Comment by pgundlupetvenkatesh** [comment]
I can still reproduce the timeout error on Watir v6.19.1. Tested with @kapoorlakshya https://github.com/kapoorlakshya/watir_iframe_switching_test code

Watir Version: 6.19.1
Selenium Version: 3.142.7
Browser Version: Chrome 89.0.4389.114
Browser Driver Version: 89.0.4389.23
OS Version: Windows 10

 ### Console output

```
$ bundle exec ruby frame_wait.rb
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:813:in `rescue in element_call': timed out after 30 seconds, waiting for #<Watir::Div: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> to be located; Maybe look in an iframe? (Watir::Exception::UnknownObjectException)
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:805:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:806:in `rescue in element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:805:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:121:in `text'
        from frame_wait.rb:15:in `<main>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:680:in `rescue in wait_for_exists': timed out after 30 seconds, waiting for #<Watir::Div: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> to be located (Watir::Exception::UnknownObjectException)
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:675:in `wait_for_exists'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:838:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:802:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:806:in `rescue in element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:805:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:121:in `text'
        from frame_wait.rb:15:in `<main>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/wait.rb:46:in `until': timed out after 30 seconds, waiting for true condition on #<Watir::Div: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> (Watir::Wait::TimeoutError)
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/wait.rb:125:in `wait_until'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:677:in `wait_for_exists'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:838:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:802:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:806:in `rescue in element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:805:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:121:in `text'
        from frame_wait.rb:15:in `<main>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:680:in `rescue in wait_for_exists': timed out after 30 seconds, waiting for #<Watir::Div: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> to be located (Watir::Exception::UnknownObjectException)
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:675:in `wait_for_exists'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:838:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:844:in `rescue in check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:837:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:802:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:121:in `text'
        from frame_wait.rb:15:in `<main>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/wait.rb:46:in `until': timed out after 30 seconds, waiting for true condition on #<Watir::Div: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> (Watir::Wait::TimeoutError)
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/wait.rb:125:in `wait_until'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:677:in `wait_for_exists'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:838:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:844:in `rescue in check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:837:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:802:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:121:in `text'
        from frame_wait.rb:15:in `<main>'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:730:in `assert_exists': unable to locate element: #<Watir::Div: located: false; {:id=>"watir", :tag_name=>"iframe"} --> {:class=>"intro", :tag_name=>"div"}> (Watir::Exception::UnknownObjectException)
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:838:in `check_condition'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:802:in `element_call'
        from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/watir-6.19.1/lib/watir/elements/element.rb:121:in `text'
        from frame_wait.rb:15:in `<main>'
IFrame found: true
```

**Comment by titusfortner** [comment]
@pgundlupetvenkatesh you need to update to Watir 7.0.0.beta2 for the fix

**Comment by pgundlupetvenkatesh** [comment]
Thank you, that worked.
